sudo: required
services: 
  - docker

before_install:
  - docker build -t abhishek-kumar-code/docker-react -f Dockerfile.dev .

  script: 
    - docker run abhishek-kumar-code/docker-react npm run test -- --coverage