suod: required
services: 
  - docker

before_install:
  - docker build -t abhishek-kumar-code/React-Application-hosted-on-a-nginx-web-server -f Dockerfile.dev .

  script: 
    - docker run abhishek-kumar-code/React-Application-hosted-on-a-nginx-web-server npm run test -- --coverage